[package]
authors = ["hhllhhyyds <hhllhhyyds@sina.com>"]
description = "Refined float with a subset of functions of std float"
edition = "2021"
keywords = ["math"]
license = "MIT"
name = "refined-float"
version = "0.1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std", "approx"]
std = []

[dependencies]
approx = {version = "0.5.1", optional = true}
libm = {version = "0.2.8", optional = true}

[dev-dependencies]
plotters = "0.3.5"

[[example]]
name = "mandelbrot"
